#!/bin/bash
#SBATCH --job-name=g4arr
#SBATCH --partition=normal
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=4
#SBATCH --mem=24G
#SBATCH --time=06:00:00
#SBATCH --output=slurm/logs/%A_%a_%x.out
#SBATCH --error=slurm/logs/%A_%a_%x.err

# EXP-04 array-job runner. Each array task reads its (seed, wd) from a manifest
# generated by submit_exp04_array.sh. Replaces the fragile external dripper.
#
# Submit with:
#   sbatch --array=0-$((N-1))%18 slurm/run_exp04_array.sh <manifest_path>
#
# Where <manifest_path> has one "<seed> <wd>" per line and N is the line count.

MANIFEST=${1:?"Usage: sbatch ... slurm/run_exp04_array.sh <manifest_path>"}
INDEX=${SLURM_ARRAY_TASK_ID:?"This script must be run as a SLURM array task"}

cd /fs1/scratch/cag1145/axiondeep-research

# Line numbers are 1-indexed; array task IDs are 0-indexed.
LINE=$(sed -n "$((INDEX + 1))p" "$MANIFEST")
SEED=$(echo "$LINE" | awk '{print $1}')
WD=$(echo "$LINE" | awk '{print $2}')

if [[ -z "$SEED" || -z "$WD" ]]; then
    echo "ERROR: manifest $MANIFEST has no entry at index $INDEX (line $((INDEX + 1)))"
    exit 2
fi

source /fs1/scratch/cag1145/persist-env/bin/activate
export CLEARML_OFF=1
export PYTHONUNBUFFERED=1

WD_TAG=$(printf "%.2f" "$WD")
OUT_DIR="results/exp04_full/wd_${WD_TAG}"

echo "============================================"
echo "Array job: $SLURM_ARRAY_JOB_ID task: $SLURM_ARRAY_TASK_ID"
echo "Manifest:  $MANIFEST (line $((INDEX + 1)))"
echo "Seed:      $SEED"
echo "WD:        $WD (dir tag: $WD_TAG)"
echo "Output:    $OUT_DIR"
echo "Node:      $SLURMD_NODENAME"
echo "GPU:       $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'N/A')"
echo "Date:      $(date)"
echo "============================================"

mkdir -p "$OUT_DIR"

/fs1/scratch/cag1145/persist-env/bin/python -m experiments.exp04_grokking_topology.run_pilot \
    --config configs/exp04_full.yaml \
    --seed "$SEED" \
    --weight-decay "$WD" \
    --output-dir "$OUT_DIR"

EXIT_CODE=$?
echo "Exit code: $EXIT_CODE"
echo "Finished:  $(date)"
exit $EXIT_CODE
